### ISSUE TITLE
Wrong keywords in forwardingList

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/AdministratorAdministration#206]
I noticed that in the forwarding list there are keywords "server-name" and "service-name".
In the template from the ApplicationPattern I only see "server-name", so I guess this might be wrong as I would expect this should be "server-name" everywhere...

Example:
```
  - forwarding-name: ServiceRequestCausesLtpDeletionRequest
    uuid: aa-2-0-1-op-fc-bm-007
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
        - server-name: /v1/redirect-topology-change-information
          uuid: aa-2-0-1-op-s-bm-009
      fc-port-update:
        - server-name: /v1/redirect-topology-change-information
          uuid: aa-2-0-1-op-s-bm-009
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - service-name: /v1/disregard-application
        uuid: aa-2-0-1-op-s-is-002
    consequent-requests:
      - client-name: ApplicationLayerTopology://v1/delete-ltp-and-dependents
        uuid: aa-2-0-1-op-c-bm-alt-1-0-0-002
```
